label ch4_main:
    stop music fadeout 2.0
    scene bg residential_day
    with dissolve_scene_full
    
    play music t6

    "Bugün pazar günü."

    if ch4_scene == "natsuki":
        "Natsuki'nin gelecek ziyareti hakkında gittikçe daha fazla endişeleniyorum."
        "Kendime, gergin olmam için bir sebep olmadığını söylüyorum ama pek fayda etmiyor."
        "Sadece ikimiz olduğunda nasıl davranacak acaba?"
        "Bu arada, sürekli bana mesaj atıyor."
        "Numaralarımızı birbirimize verdikten sonra bir iki mesajlaştık ama bu, sohbet haline dönüştü."
        "Telefonla çok farklı bir kişilik gibi, her mesajda bolca emoji ve tatlı bir dil kullanıyor."
        "Ayrıca sürekli şikayet ediyor, ama bunu tahmin etmiştim."
        "Ama Natsuki'yi bir kenara bırakacak olursak..."
    else:
        "Yuri'nin gelecek ziyareti hakkında gittikçe daha fazla endişeleniyorum."
        "Kendime, gergin olmam için bir sebep olmadığını söylüyorum ama yine de yardımcı olmuyor."
        "Yuri kesinlikle bir içe dönük biri ve genelde oldukça mahrem bir insan."
        "İkimiz olduğunda biraz daha açılacağından şüphem yok."
        "Bu arada, zaman zaman mesajlaşıyoruz."
        "Başlangıçta oldukça çekingen davrandı ama çok geçmeden, onu daha fazla tanımaya başladım."
        "Ama Yuri'yi bir kenara bırakacak olursak..."
    "Sayori'den, o günden beri hiçbir haber almadım."
    "Her zaman birbirimize mesaj atıyoruz dememek lazım ama..."
    "Zihnimde onunla ilgili endişeleniyorum."
    "Sayori'nin söyledikleri ve Monika'nın söyledikleri arasında..."
    "Sayori belki de bana ihtiyacı olduğu zamanlarda, duygularını bir kenara bırakmam doğru olur mu?"


    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "Sayori'yi [ch4_name] gelmeden önce ziyaret etmeye karar veriyorum."
    "Sormak yerine, sadece \"Geliyorum\" diyorum, tıpkı geçmişte olduğu gibi."
    "Sayori'nin evine vardığımda, kapıyı çalıp içeri giriyorum."
    "Yine, o kadar çok oynardık ki, birbirimizin evlerine sanki ailemizmişiz gibi girmeyi alışkanlık haline getirmiştik."

    scene black with wipeleft
    "Ev oldukça sessiz."
    "Sayori, ilk katta gözükmüyor, bu yüzden üst katına gitmiş olmalı."
    "Beni karşılamadan aşağıya koşmaması çok garip."
    "Odanın kapısını çalıp, nihayet onu buluyorum."

    scene bg sayori_bedroom with wipeleft
    mc "Sayori?"
    play music t10
    show sayori 1ba at t11 zorder 2
    s "Merhaba [player]~"
    show sayori 1by
    "Odasına oturuyorum."
    "Sayori gülümsemeye çalışıyor ama, onun farklı olduğunu hemen anlayabiliyorum."
    "Aramızda bir dakika kadar bir sessizlik var."
    s "Beni uzun zamandır böyle görmedin, değil mi?"
    mc "Ah... sanırım haklısın."
    mc "Gerçekten uzun bir zaman oldu."
    mc "Ama pek bir şey değişmemiş, değil mi?"
    "Sayori'nin odası, her zamanki kadar dağınık."
    "Yıllardır aynı peluş oyuncakları ve duvar süsleri olduğunu fark ediyorum."
    s 2bl "Ehehe~"
    s "Daha sık gelseydin, böyle dağılmazdı."
    mc "Çünkü ben senin için hep temizliyorum..."
    s 1bb "Bugün aniden gelmene ne sebep oldu?"
    s "Bugün [ch4_name] ile buluşmayacak mıydın?"
    mc "Evet, ama..."
    mc "...Bekle, bunu nasıl bildin?"
    "Sayori, o toplantıda ayrıldığında zaten bu konuda bir şey söylememişti."
    s 1ba "Monika bana söyledi."
    s "Onun festival hazırlıkları hakkında beni bilgilendirmesi çok normal, değil mi?"
    mc "Ah, doğru..."
    mc "Ama ya sen?"
    mc "Bugün Monika'ya yardım etmiyor musun?"
    s 4bb "Tabii ki!"
    s "Ama sadece online yardımcı oluyorum."
    s "Birlikte buluşmayı planlamadık."
    mc "Ah, yani sadece ben ve [ch4_name] varız, öyle mi?"
    s 1ba "Evet~"
    "Aramızda bir sessizlik daha var."
    show sayori 1bk
    "Sayori, rastgele bir yere bakıyor."
    "Davranışlarının her şeyi gerçekten alışılmadık."
    "Nihayet konuya geliyorum."
    mc "Ben sadece... senin nasıl olduğunu görmek istedim."
    mc "Cuma günü ayrıldığından beri."
    mc "Bir şeyler ters gitmişse, bunu benden saklayamazsın!"
    mc "Seni çok iyi tanıyorum."
    mc "Yani..."
    "Sayori gülümsüyor, başını sallıyor."
    s 1bd "Bu doğru değil, [player]."
    mc "Eh?"
    s "Neden her şey eskisi gibi olamaz ki?"
    s 1by "Her şey benim suçum."
    s "Eğer bu kadar zayıf düşmeseydim ve duygularımı yanlışlıkla ifade etmeseydim..."
    s 1bk "O kadar aptalca bir hata yapmasaydım..."
    s "O zaman sen beni hiç endişelenmeyecektin."
    s "Buraya gelmeyecektin."
    s 1bd "Şu anda beni düşünmeyecektin bile."
    s "Ama bu... sadece cezam, değil mi?"
    s "Kendimi bu kadar bencil olduğum için cezalandırılıyorum."
    s "Sanırım bu yüzden dünya, bugün buraya gelmeni istedi."
    s "Beni eziyet etmek istiyor."
    s 4bq "Ehehe~"
    mc "Sayori!"
    show sayori 4bb
    "Sayori'yi omuzlarından tutuyorum."
    mc "Ne diyorsun sen?!"
    mc "Kendini duyuyor musun şu anda?"
    mc "Bir şeylerin olduğuna eminim."
    mc "Bunun başka bir açıklaması yok."
    mc "O yüzden bana anlat, hemen...!"
    mc "Bunu öğrenmeden bir an bile düşünemem!"
    s 4bl "Ah..."
    s "Ahaha..."
    "Sayori boş bir gülümseme atıyor."
    s 4by "Beni gerçekten bir tuzağa düşürdün, [player]."
    s "Ama..."
    s 1ba "Yanılıyorsun."
    s "Bana hiçbir şey olmadı."
    s "Ben her zaman böyleydim."
    s "Sen bunu ilk defa görüyorsun."
    mc "Ne görüyorsun?"
    mc "Ne demek istiyorsun, Sayori?"
    s 1bq "Ehehe~"
    s 1ba "Gerçekten bunu söylememi istiyorsun, değil mi, [player]?"
    s "Sanırım bu kez başka seçeneğim yok."
    s 1bc "Aslında..."
    s "Hayatım boyunca çok kötü depresyonum vardı."
    s 1bb "Bunu biliyor muydun?"
    s "Neden her gün okula geç kaldığımı sanıyorsun?"
    s "Çünkü çoğu gün, yataktan çıkmak için bir neden bile bulamıyorum."
    s 1by "Ne anlamı var ki bir şeyler yapmanın, kendimin ne kadar değersiz olduğunu tam olarak biliyorken?"
    s "Neden okula gideyim?"
    s "Neden yemek yiyeyim?"
    s "Neden arkadaş edineyim?"
    s "Neden başkalarının zamanını ve enerjisini, benden fayda sağlamak yerine bana harcattırayım?"
    s "Bana böyle hissettiriyor."
    s "Ve bu yüzden ben sadece herkesi mutlu etmek istiyorum..."
    s "Kimse beni düşünmesin diye."
    mc "..."
    "Şok olmuş durumdayım."
    "Ne diyeceğimi bilemiyorum."
    "Sayori, tüm bu zaman boyunca bunu benden saklayabilmiş miydi?"
    "Gerçekten benim sadece onu düşünmememi mi istemişti?"
    mc "...Neden, Sayori?"
    s 1bg "Eh...?"
    mc "Neden bana bunu hiç söylemedin, Sayori?"
    mc "Hissettiğim şey, senin en yakın arkadaşın olarak biraz kandırılmış gibi hissetmem."
    mc "Çünkü eğer bilseydim, sana yardımcı olmak için elimden geleni yapardım!"
    mc "Sadece yapabileceğim çok az şey olsa bile..."
    mc "Her günü senin için biraz daha güzel hale getirebilmek için biraz daha fazla çaba gösterirdim."
    mc "Bu yüzden ben senin arkadaşıyım!"
    mc "Tek yapman gereken bana söylemekti!"
    s 1bk "Hiçbir şey anlamıyorsun, [player]."
    s "Neden sana söylemedim sanıyorsun?"
    s 1bd "Çünkü eğer söyleseydim, o zaman senin de bana değer vermen gerekecekti, ama ben istemiyorum ki, sen zamanını ve çabanı benim için harcayasın, önemli şeyler yapman yerine."

    s "Benimle ilgilenmeni istemiyorum."
    s "İnsanlar benimle ilgilenmeye çalıştığında, tatlı bir acı gibi hissediyorum."
    s 1ba "Bazen güzel hissettiriyor."
    s "Ama aynı zamanda kafama bir sopanın vurulmuş gibi hissediyorum."
    s 4bq "Ahaha~"
    s 4ba "Bu yüzden seni başkalarıyla arkadaş yapmanı çok istedim..."
    s "Herkesin birlikte mutlu olmasına yardımcı olmak benim için en iyi şey."
    s 1bb "Ama sonra başka bir şey daha keşfettim."
    s "Seni, kulüpteki herkesle arkadaş olup yakınlaşırken görmek..."
    s 1bk "Kalbime bir mızrak saplanıyormuş gibi hissettirdi."
    s "Yani, işte bu yüzden."
    s "Bu yüzden dünyaya, beni sadece eziyet etmek istiyormuş gibi geliyor."
    s 1by "Her yol sadece acıya çıkar."
    s "Ahaha~"
    mc "Haklısın, anlamadığımı kabul ediyorum..."
    mc "Sayori, duygularını hiç anlamıyorum."
    mc "Ama anlamama gerek yok."
    mc "Sadece senin acı çekmeni durdurabilmek için ne gerekiyorsa yapacağım..."
    mc "Bunu yapacağım."
    s 1bd "Hayır, [player]."
    s "Hiçbir şey."
    s "Hiçbir şey yok."
    s "Yardım edebilecek tek şey, her şeyin eskisi gibi olmasıydı."
    s 1bk "Ama ben bencildim."
    s "Sonunda sana ne kadar korkunç biri olduğumu gösterdim."
    "Sayori'nin yüzünden yaşlar süzülür."
    s 1bv "Seni edebiyat kulübüne katılmaya zorladım, çünkü bencildim."
    s "Ve kalbim, anlayamadığım bir şekilde acıdığı için cezalandırıldım."
    s "Ve şimdi geldin ve seni de acıttım."
    s 1bt "Ben sadece zayıf ve bencildim."
    s "Ben sadece böyleyim."
    s "Ve bu yüzden bu cezalara katlanacağım."
    s 1bv "Çünkü her birini hak ediyorum...!"
    "Hiç düşünmeden, Sayori'nin omuzlarını tekrar sımsıkı tutuyorum."
    "Bu sefer onu sıkıca kucaklıyorum."
    scene black with dissolve_cg
    s "A-Ah--"
    s "[player]..."
    mc "Sayori."
    mc "Bencillik hissetsen bile umurumda değil."
    mc "Kulübe katılmamı sağladığın için gerçekten mutluyum."
    mc "Seni her gün görmek, her şeye değer."
    mc "Eğer başkalarıyla arkadaş olursam, o sadece bir bonus olur."
    mc "Ama lütfen benim seni ne kadar önemsediğimi asla küçümseme."
    mc "Bunu başka türlü istemezdim."
    s "[player]..."
    "Sayori, bana karşılık vermiyor."
    "Kollarım etrafında sarılı olmasına rağmen, Sayori'nin kolları yanlarında kalıyor."
    "Kulaklarımın yanında hıçkırıklara başlıyor."
    s "Hayır..."
    s "Bunu bana yapma..."
    s "Lütfen bunu bana yapma..."
    s "[player]..."
    s "Ben..."
    "Sayori, hıçkırıkları arasında zar zor konuşabiliyor."
    "Doğru şeyleri yapıp yapmadığımı bilmiyorum."
    "Ama tek istediğim, ona değer verdiğimi hissettirmem."
    mc "Eğer kendini bencil olarak nitelendirebiliyorsan, o zaman benim de bencil olmama izin vermelisin."
    mc "Ne olursa olsun, neyin değişmesi gerektiğini anlayacağım."
    mc "Bu duyguları ortadan kaldıracağım."
    mc "Ve eğer yapmam gereken bir şey varsa..."
    mc "O zaman bana söylemelisin."
    mc "Söylemezsen kızarım."
    s "..."
    s "Bilmiyorum..."
    s "Bilmiyorum..."
    s "Bilmiyorum."
    "Nazikçe, Sayori nihayet bana sarılıyor."
    s "Hiçbir şey bilmiyorum."
    s "Her şey gerçekten çok korkutucu..."
    s "Duygularımı hiç anlamıyorum, [player]..."
    s "Hiçbir şey hissetmediğim tek zaman, acı hissettiğim zaman."
    s "Ama..."
    s "Senin kucaklamaların o kadar sıcak..."
    s "...Ve bu da gerçekten korkutucu."
    scene bg sayori_bedroom
    show sayori 1bv at i11 zorder 2
    with dissolve_cg
    "Sayori beni bırakıyor."
    "Bunu yaparken, ben de onu bırakıyorum."
    mc "Festival yarın."
    s 1bk "Evet..."
    mc "Eğlenceli olacak, değil mi?"
    s "Evet."
    mc "Tüm günü seninle geçirmemi ister misin?"
    s 1bh "E-Eh..."
    s "Ah--"
    mc "Bu istediğim şey."
    mc "Söz veriyorum."
    s 1bk "Ben..."
    s "Sanırım bu güzel olur..."
    mc "Evet."
    "Sayori gözlerini siliyor."
    "Keşke bütün günü burada geçirebilseydim."
    mc "Tüm günlerden, neden bu gün başka planlarım var..."
    mc "Belki iptal etmeliyim--"
    s 1bh "Hayır, yapma--!"
    s 1bg "Lütfen yapma..."
    s "Eğer yaparsan... o zaman gerçekten seni affetmem."
    mc "Ama..."
    mc "Neredeyse [ch4_name] evime gelmeye başlayacak..."
    mc "En azından, gelmek ister misin ve yardım etmek ister misin?"
    mc "Eğlenceli olurdu."
    "Şaşırtıcı bir şekilde, Sayori başını sallıyor."
    s 1bd "Üzgünüm."
    s "Bugün bunu benim için yapmak pek iyi olmaz sanırım."
    s "Anlıyorsun, değil mi?"
    mc "Ah..."
    mc "Bunu tamamen anlamam biraz zor..."
    mc "Ama elimden geleni yapıyorum."
    s "Sorun değil."
    s "Çok fazla üzülme."
    s 4ba "Yarın görüşürüz, tamam mı?"
    mc "...Tamam."
    mc "Sabırsızlanıyorum."
    # Sayori rotası ise, geri dön
    # kısa özet: bir başka kızla 3 puan alman lazım, onunla gidersen Sayori rotasına gidersin, 2/2 gidersen Sayori'ye yönlendirilirsin
    if(yuriRoutePoints>=3 or natsukiRoutePoints>=3):
        # normal şekilde devam et
        scene bg residential_day with wipeleft_scene
        $sayoriRoute = False
    else:
    # Sayori'nin rotası tetiklendi
        #m "lol filler"
        $sayoriRoute = True
        return

    "Sayori'ye veda ediyorum ve evinden çıkıyorum."
    "Eve giderken hâlâ kendimi huzursuz hissediyorum."
    "Ama [ch4_name] da gelmek üzere olduğu için buna daha fazla takılmak zor..."
    "Sanırım Sayori haklı."
    "Çok fazla endişelenmemeliyim, ve yarın kesinlikle harika vakit geçireceğiz."
    "Sadece önümdekine odaklanmalıyım!"
    call expression "ch4_exclusive_" + ch4_scene
    call ch4_end

    return


    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    $natsukiRoute = True
    "Evde sadece birkaç dakika geçirdikten sonra, Natsuki'nin gelişini sabırsızlıkla bekliyorum."
    "Farkına varmadan, bana dışarıda olduğunu haber veren bir mesaj atıyor."
    "Hiç vakit kaybetmeden, ön kapıyı açıp onu içeri alıyorum."
    show natsuki 2bj at t11 zorder 2
    mc "..."
    n "'Ne var?" 
    mc "...Merhaba."
    "Ne bekliyordum tam olarak bilmiyorum ama, Natsuki'yi okul kıyafetlerinin dışında görmek beni gerçekten şaşırttı."
    "Onu bu kadar şirin kıyafetlerle görmek, üniformayı tamamen uyumsuz hale getiriyor."
    n 4bc "Aman Tanrım, bu kadar garip olma!"
    n "Uzun bir öğleden sonra geçireceğiz, yani okul dışında beni böyle görmek garip olmasın."
    n "Neyse, içeri giriyorum."
    scene bg kitchen
    show natsuki 1bj at t11 zorder 2
    with wipeleft
    mc "Bir sürü şey getirmişsin..."
    "Natsuki, muhtemelen fırın malzemeleriyle dolu büyük bir çanta taşıyor."
    n 2bj "Yani, bu kadar yol geldim, senin mutfakta iş yapacak malzemeler olmadığını öğrenmek istemedim."
    n "Bana istediğim her şeyi aldın, değil mi?"
    mc "Evet, aldım."
    "Dün, Natsuki benden evde eksik olan malzemeleri almak için bir sürü malzeme almıştı."
    n 2bl "İyi!"
    n "Demek ki seninle güvenebileceğimi düşünüyorum."
    mc "Tabii..."
    "Natsuki'nin bana bu şekilde teşekkür etmesi, genellikle sergilediği sert tavırlardan çok farklı."
    "Acaba okul dışında biraz farklı mı davranıyor gerçekten?"
    mc "Neyse, hadi mutfağa gidelim..."
    n 2by "Ne yani, bu ağır çantayı almaya teklif etmeyecek misin?"
    n "Misafirperverliğin nerede, [player]?"
    mc "Hadi ya..."
    mc "Ne zaman bir centilmen olmam gerekiyordu ki?"
    "Natsuki'nin bana uzattığı çantayı alıyorum."
    mc "Ghk--"
    mc "Bu inanılmaz derecede ağır--!"
    n 4bz "Ahaha!"
    n "Bunu buraya kadar ben taşıdım."
    n 4bl "Hayran kaldın mı?"
    mc "Şimdi anlıyorum..."
    mc "Evet, gerçekten hayran kaldım, Natsuki."
    mc "Sürekli seni hafife aldığımı fark ettim."
    n 4by "Ehehe~"
    n "Çünkü çok küçüğüm, değil mi?"
    n 4ba "Sen haksızsın."
    "Natsuki yumruğunu göğsüme vuruyor."
    mc "Hey, hey."
    mc "Boyunun bununla bir ilgisi yok."
    mc "Gerçekten küçük olmanı bu kadar mı sevmiyorsun?"
    n 1bk "Hı?"
    n "E..."
    n 1bc "Bundan nefret etmiyorum..."
    n "Yani, bazen insanlara sadece boyumla değer verildiğini kanıtlamayı seviyorum."
    n 1ba "Küçük olup, diğerlerinden daha iyi olduğumu görmek eğlenceli."
    n "Ama..."
    n 5bw "...Aman Tanrım, boş ver!"
    n "Ne diyeceğimi yapma!"
    n 5bq "Okul dışında olduğumuzu düşünerek garip şeyler söylettirmeye çalışma!"
    n "Başlıyoruz muyuz, yoksa? Çünkü öğretmem gereken çok şey var."
    mc "Ahaha."
    n 5bn "Ne??"
    mc "Bu biraz daha sana benziyor."
    mc "Bana böyle doğrudan konuştuğunda daha eğlenceli oluyorsun."
    n 1bm "H-Hey!"
    n "Şimdi {i}çocuk{/i} gibi mi davranıyorsun bana?"
    n "Biraz sana nazik olmaya çalışıyordum, biliyor musun."
    n 1br "Ve sadece Yuri gibi olgun ve seksi bir vücuda sahip olmadığım için bana..."
    n 1bo "A-Ah--"
    "Natsuki, kelimelerini yakalıyor ve yüzü kırmızılaşıyor."
    mc "Natsuki..."
    n 1bp "Boşver!"
    n "Hiçbir şey demedim!"
    mc "Özür dilemeliyim."
    n 1bh "Hı?"
    mc "Daha nazik olmaya çalıştığını takdir ediyorum."
    mc "Ben de biraz daha dikkatli olmalıydım."
    mc "Ama ayrıca..."
    mc "Eğer bunu düşünüyorsan, bilmelisin ki vücut tiplerine ilgi duyan bir sürü erkek var."
    n 1bq "Ah..."
    n "Nasıl... bunu biliyorsun ki?"
    mc "Bana güven bu konuda."
    n "..."
    n 5bx "...İğrenç."
    mc "Hey!"
    mc "Bu bana mıydı?"
    n 5bw "Başka kim?"
    mc "Adamım..."
    mc "Hadi başlayalım artık."
    n 2bl "Ahaha!"
    n "Bir kız seni iğrenç diye çağırınca surat asıyorsun."
    n 2bd "Nihayet zayıf noktanı buldum, [player]."
    "Natsuki sinsi bir şekilde gülümsüyor."
    mc "Beni bırak..."
    "Neyse, Natsuki eğer böyle hakaretler etmeye devam ederse, geri adım atmam söz konusu olamaz."
    "Ama şimdilik yeterince tatmin olmuş gibi görünüyor, nihayet çantasındaki şeyleri çıkarıp başlamak üzere."

    scene bg kitchen
    with wipeleft_scene
    "Kısa süre içinde, mutfak tamamen dağılmış durumda."
    "Kaşıklar, kirli kaseler, un, dökülen sıvılar ve plastik torbalar her yerde dağınık bir şekilde yer alıyor."
    "Mikser, bütün hamuru bir seferde yapacak kadar büyük değil, bu yüzden birkaç kez yapmak zorunda kaldık."
    "Bu arada, Natsuki bütün hareketlerimi izleyip hamurun bozulmaması için dikkatli olmamı sağlıyor."
    show natsuki 2bk at t11 zorder 2
    n "[player], gıda boyasını nereye koydun?"
    n "Hamur fırına girmek üzere, bu yüzden tepsileri doldurmam gerek."
    mc "Sanırım hala masanın yanındaki çantada."
    mc "Ne için kullanıyorsun?"
    n 4bl "Tabii ki hamuru renklendirmek için!"
    n 4bj "Her tepsiyi farklı bir renkte yapıyorum."
    n "Böylece tatlar farklı olmasa da herkes kendi favorisini seçebilir."
    mc "Aa, bu tatlı bir fikir."
    mc "Peki, icing'le de bir şeyler yapacak mıyız?"
    n 4bk "Yapmak ister misin?"
    mc "Aa..."
    mc "Bana mı soruyorsun?"
    mc "Aslında bir tercihim yok, o yüzden..."
    n 1bm "Hadi ama..."
    n "Buna hiç kalp koymuyorsun!"
    n "Biraz eğlenmeye çalışamaz mısın?"
    mc "Eğleniyorum aslında..."
    "Gerçekten Natsuki'nin benden ne beklediğinden emin değilim."
    "Bu arada, Natsuki hamuru küçük kaselere ayırıp her birine birkaç damla gıda boyası koyuyor."
    mc "Aa, gerçekten çok hoş görünüyor."
    n 2bj "Gördün mü?"
    n "Biliyor musun, pasta yapmak sadece tarife uymakla ilgili değil."
    n "Sunum, yaratıcı olabileceğin ve eğlenebileceğin yerdir."
    n "Sonunda sadece bakmak bile herkesin gözlerini parlak hale getirdiğinde, her şeye değer."
    mc "İlk günümde yaptığın kekler gibi mi?"
    "Natsuki'nin gururla sunduğu kedi şeklindeki kekleri ve Sayori ile Monika'nın mutlu yüzlerini hatırlıyorum."
    "Bunu başarmamı sağlayacak mıyım, merak ediyorum."
    mc "Evet..."
    mc "Sanırım gıda boyasını kullanacağım."
    n "Bunu anlamaya başladığını görmek güzel."
    n "Ama frosting'i tamamen karıştırmadan gıda boyasıyla oynama, tamam mı?"
    mc "Evet, yavaş yavaş oluyor."
    "Hamuru mikserle yapıyorduk, bu yüzden frosting için bir çırpıcı ve büyük bir kaseyle kaldım."
    n 4bc "Eh?"
    n "Frosting hala lumpy!"
    n "Gerçekten deniyor musun?"
    mc "Evet, tabii..."
    mc "Biraz daha uzun sürecek sadece."
    n 4bg "Vay canına, böyle devam edersen bütün gece burada olacağım."
    n "Bak, şöyle yap."
    "Natsuki çırpıcıyı benden alıyor ve diğer eliyle kaseyi geri eğiyor."
    n 4be "Gerçekten...şunu...dövmelisin!"
    "Birkaç saniye sonra, frosting'in kıvamı zaten iyileşiyor."
    n 4ba "Görüyor musun?"
    "Vurgulamak için, Natsuki parmağını frosting'e batırıp ağzına atıyor."
    "Ben de isteksizce aynı şekilde yapmaya başlıyorum."
    n 1bh "Hey!"
    "Natsuki aniden bileğimi tutuyor."
    n 4bh "Sadece...senin...iğrenç parmaklarını frosting'ime koyma!"
    mc "Frosting'in mi, ha?"
    mc "Kim yaptı bütün bu işi unuttun mu?"
    "Parmağımı kaseye doğru ittirmeye başlıyorum."
    n 4by "Bir de...beni dövmemi mi istiyorsun?!"
    mc "Denemeni isterim!"
    "Daha fazla itiyorum, parmağım tam olarak frosting'e ulaşıyor."
    "Zaferle, parmağımı aldığımda Natsuki bütün gücüyle beni çekiyor."
    mc "Ah--!"
    "Natsuki'yi çekmem, onu sende düşürmek zorunda bırakıyor."
    n 1bx "İğrenç!"
    n "Yüzüme koydun!"
    mc "Bunun suçu kimde?!"
    "Natsuki'nin yanağında büyük bir frosting topu var."
    n 1bw "Nnn--"
    "Dilini uzatıp ulaşmaya çalışıyor ama çok uzak."
    n 1br "Vay be..."
    n "Biliyorsun ne mi?"
    n 4bd "Bunu al!"
    "Natsuki, parmağını silip kendi parmağını yüzüme doğru itiyor."
    mc "Hadi ama--!"
    "Ben daha hızlıyım."
    "Parmağını tutup, kendi parmağımı onun yüzüne sokuyorum."
    $ persistent.clear[4] = True
    scene n_cg3_base
    show n_cg3_exp1
    show n_cg3_cake
    with dissolve_cg
    n "Ahahaha! Dur!"
    mc "Taşınmadan önce iğrenç demek için özür dilemen lazım!"
    n "Tamam, tamam!"
    n "Sana iğrenç demek için özür dilerim."
    n "Biliyorsun, bunu gerçekten demek istemedim."
    n "Sadece seni tepki verirken görmek çok eğlenceli."
    n "...Bunu hep yapıyorsun zaten!"
    n "Saçma şeyler söyleyip beni tepki vermeye zorlamak."
    n "Gerçekten böyle kızlara takılmamalısın."
    mc "Öyle mi?"
    mc "O zaman, bunu da yapmamalıydım sanırım..."
    show n_cg3_cake at cgfade
    hide n_cg3_cake
    "Parmağını alıp ağzıma koyuyorum, frosting'i yalayarak."
    show n_cg3_exp1 at cgfade
    show n_cg3_exp2 at cgfade
    hide n_cg3_exp1
    n "W-W-What--?"
    n "D-Demek gerçekten--"
    n "A-Ah--"
    "Natsuki o kadar şaşkına dönüyor ki, bana nasıl kızacağını bile bulamıyor."
    "Yüzü tamamen kırmızı."
    hide n_cg3_exp2
    n "[player]..."
    n "Gerçekten kızlara böyle şeyler yapmamalısın... eğer onlara gerçekten hoşlanmıyorsan..."
    n "Bunu biliyorsun, değil mi?"
    mc "..."
    "Hangi soru bu, böyle mi hemen?"
    "Nasıl böyle bir hava oldu?"
    mc "Ben..."
    "Natsuki sessizce bana bakıyor."
    "Hızlı nefes aldığını fark ediyorum."
    "Neden birden başım dönmeye başladı...?"
    n "Eh?!"
    scene bg kitchen with dissolve_cg
    "Birden bire, yangın alarmı çalmaya başlıyor."
    "Natsuki hızla fırına yöneliyor."
    mc "Bir şey mi yanıyor?"
    mc "Sanırım daha önce kekleri koymadın."
    show natsuki 1bw at t11 zorder 2
    n "{i}*Öksürük*{/i}"
    n "Anlaşıldı..."
    n 1bb "Kirli bir tepsi bırakmışsın, aptal!"
    n "Bunu nasıl unuttun?"
    mc "Fırını açmadan önce kontrol etmeliydin!"
    n 1bs "Beni suçlama!"
    n "Vay be..."
    "Natsuki, fırın eldiveniyle, siyahlaşmış tepsiyi fırından çıkarıyor."
    "Tepsiyi ocağın üstüne koyuyor."
    "Birkaç saniye sonra, yangın alarmı duruyor."
    n 1bq "Her neyse..."
    n "Şimdi... kekleri fırına koyuyorum."
    mc "Evet..."
    "Önceki anın gerginliği hala başımızın üstünde asılı kalmış durumda."
    "Ama o an zaten kaybolmuş."
    "Natsuki, kek tepsilerini fırına koyarken izliyorum."
    "Sonra, isteksizce çırpıcıyı alıp icing'e devam ediyorum, sanki hiçbir şey olmamış gibi."

    scene bg kitchen
    show natsuki 4bz at t11 zorder 2
    with wipeleft_scene
    n "Ahh, ne kadar güzel kokuyorlar!"
    "Kekler fırından çıkarmaya hazır."
    "Natsuki fırının kapağını açar açmaz, o tatlı kokulu sıcak hava odayı dolduruyor."
    n 4bl "Bak ne kadar tatlı görünüyorlar!"
    "Her bir tepsideki farklı renkli kekleri gururla gösteriyor."
    mc "Üstlerine krema sürünce daha da güzel olacaklar."
    n 2ba "Bunu bana {i}söylemene{/i} gerek yok!"
    n "Dekorasyon malzemeleri getirdim, umarım yaratıcı olabilirsin."
    n "Al, kremayı bu poşetlere koy."
    "Natsuki bana birkaç plastik poşet verir."
    n 2bj "Bu nozüller var, bunlarla çok güzel ve kabarık bir şekilde süsleyebilirsin."
    n "Bununla çiçek bile yapabiliyoruz!"
    n "Ama sanırım bu sefer kullanmayız."
    mc "Peki bu ne için?"
    "Diğerlerinden çok daha ince bir ucu olan bir nozüldeki poşeti alırım."
    n 4bk "O çok ince, bu nozüleyle çizgiler veya farklı desenler yapabilirsin."
    n "Ama aynı zamanda pastaya yazı yazmak için de kullanabilirsin."
    n "Mesela 'doğum günün kutlu olsun!' gibi bir şey."
    mc "Hı, anladım..."
    mc "Aslında bana bir fikir verdi."
    n "Ehh?"
    mc "Yani, bu bir edebiyat etkinliği, değil mi?"
    mc "Her bir keke farklı bir kelime yazarsak, etkinliği daha edebiyat temalı hale getirebiliriz."
    mc "Herkesin sevdiği bir kelimeye göre kek seçmesi eğlenceli olur."
    n 1bq "Uu..."
    mc "Hı?"
    n "Normalde gerçekten aptalca bir şey söylemeni bekliyordum..."
    n 1bs "Ama aslında... çok tatlı bir fikir, yani..."
    mc "Ahaha."
    mc "Belki bunu senden alıyorum."
    n 5bh "B-Bu ne demek şimdi?"
    n "Ben tatlı falan değilim!"
    mc "Hadi ama..."
    mc "Okulda değiliz, kimse seni yargılamaz."
    mc "Böyle giyinip böyle davranıp tatlı olmamı beklememelisin."
    n 5bs "W-Well..."
    "Natsuki'nin sesi kesilir."
    n "Seninle de aynı..."
    mc "Ehh?"
    mc "Bir şey söyledin mi?"
    n 1bw "H-Hayır, bir şey söylemedim!"
    n "Hadi krema sürmeye başlayalım!"
    "Natsuki hızlanır ve her poşetin ucuna bir nozul takar."
    n 1bh "Yapılacak çok iş var, vakit kaybetmemeliyiz!"
    "Al, sana nasıl yapılacağını göstereyim."
    "Natsuki bana düşünmeye fırsat vermeden hızlıca devam eder."
    "Kremayı nasıl süreceğimizi gösterir ve sonra her birimiz işe koyuluruz."


    scene bg kitchen with wipeleft_scene
    "Nihayet bitirdiğimizde, Natsuki hepsini yan yana koyup yaptığımız işi hayranlıkla izliyor."
    show natsuki 4bl at t11 zorder 2
    n "Birlikte ne kadar güzel görünüyorlar!"
    mc "Evet, gerçekten de öyle, değil mi?"
    n 1bm "Uu... Keşke şimdi bir tane yiyebilsem!"
    mc "Buna engel olmanın bir anlamı yok, değil mi?"
    mc "Bunda bir sakınca görmüyorum."
    n 1bc "Ehh, evet ama..."
    n "Bugün akşam yemeğini babam yapacak, bu yüzden iştahımı korumam gerek."
    mc "Ahaha."
    mc "Sayori bu konuda tam tersi."
    mc "Eğer burada olsaydı, zaten on kekin hepsini yemiştik bile."
    mc "Ve hâlâ akşam yemeğini yerdi."
    n 4bg "Hadi canım, bu gerçekten sağlıksız!"
    n 4bs "Hem de, babam yemek yaparsa, her şeyin tadını çıkarıp yemeliyim..."
    n 4bq "...Neyse, her neyse!"
    n 4bc "Manga okumaya vaktimiz olur diye umuyordum, ama akşam yemeği için evde olmam gerek..."
    mc "Ah, zaten mi?"
    mc "Yazık oldu."
    n 1bg "Hızlı çalışmadığın için suçlu sensin!"
    n "Bunu düşünmeliydin."
    n "Bu fırsat her zaman olmayacak gibi."
    mc "Vah..."
    "Her zamanki gibi, suçlu ben oluyorum."
    n 2bk "Yarın kekleri getirebilirsin, değil mi?"
    n "Eğer Sayori ve sen her birinizi taşırsanız, sanırım tek bir gidişte götürebilirsiniz."
    mc "Evet, bunu yapabilirim."
    mc "Ve merak etme, ona kek yedirmem."
    n 2ba "Ahaha."
    n "Keşke o da bana senin gibi dinlese."
    mc "Ah..."
    mc "Evet."
    show natsuki at thide zorder 1
    hide natsuki
    "Yine, bu sabah Sayori ile yaptığım konuşmayı hatırlıyorum."
    "Kendimi çok çaresiz hissetmiştim."
    "Sayori her zaman beni dinler, ama o an sanki hiç dinleyemezmiş gibi hissettim."
    show natsuki 4bl at t11 zorder 2
    n "Tamam, her şey paketlendi."
    n "Bugün iyi iş çıkardık!"
    mc "Sen de."
    mc "Seni uğurlayayım... sanırım."

    scene bg house with wipeleft_scene
    "İşte böyle, Natsuki çıkmak üzere."
    "Öğleden sonranın nasıl bu kadar hızlı geçtiğine inanamıyorum."
    "Daha da önemlisi..."
    "Bu fırsatı onunla daha yakınlaşmak için değerlendirebildim mi?"
    show natsuki 1bh at t11 zorder 2
    n "Ehh..."
    n "Sanırım gideceğim..."
    n 1bq "Yardımın için teşekkür ederim, her şey için..."
    n "Yarın görüşürüz."
    mc "Dur, Natsuki."
    n 1bh "Eh?"
    mc "Önce söylediğin şey... bu fırsatın her zaman olmayacağı..."
    mc "Bunun hiç de böyle olması gerekmez!"
    mc "Bugün çok eğlendim."
    mc "Bana kek yapmayı nasıl eğlenceli hale getirebileceğini gösterdin, istediğin gibi."
    mc "Ama bunun dışında..."
    mc "Ne zaman istersen gel, tamam mı?"
    mc "Bence, mümkünse daha fazla böyle vakit geçirmek isterim."
    mc "Manga okumak istersen ya da bir yere gitmek istersen--"
    n 1bm "Ehh--"
    n "Gerçekten mi...?"
    "Natsuki, ifadesini gizlemeye çalışarak bana gergin bir şekilde bakıyor."
    mc "Evet."
    mc "Seninle daha fazla vakit geçirmek istiyorum."
    n 1bq "[player]..."
    n "Sadece bunu bitirmek istiyordun diye düşündüm..."
    n 1br "Uu..."
    n 1bn "Bugün erken gitmek zorunda kaldım, üzgünüm."
    n "Gerçekten gitmek istemedim!"
    n "Gerçekten... daha fazla kalmak isterdim."
    n "Senin gibi hissediyorum, yani..."
    stop music fadeout 2.0
    show natsuki 1bi at face with dissolve
    "Birden Natsuki bana yaklaşır."
    mc "Dur, Natsuki--"
    "Natsuki, benden çok az bir mesafe kalacak şekilde durur, bana bakar."
    "Gömleğimin kenarlarını nazikçe tutarak sanki beni tutuyormuş gibi hissediyorum."
    "Gül pembe yanakları ve aynı renkteki gözleri gözümde beliriyor, dudakları hafifçe aralanmış."
    "Ne oluyor...?"
    "Başım dönmeye başlıyor, onun yumuşak nefesini hissediyorum."
    n 1bh "Bunu hissettim..."
    n "Bir süredir..."
    n 1bo "--!!"
    show monika 1j at f41 zorder 3
    show natsuki at t22 zorder 2
    "Birden Natsuki geri sıçrar."
    n "M-monika--"
    m 1k "Hm? Beni umursama."
    mc "Monika--?!"
    mc "Sayori sana sadece çevrimiçi yardım ediyordu demişti--"
    m "Fikrimi değiştirdim, gelmeye karar verdim."
    #mc "Her neyse, az önce--"
    mc "Her neyse, Monika, az önce--"
    m 3b "Haha, merak etme."
    m "Sırrınız bende güvende~"
    m "Sayori'nin evine gidiyordum, çünkü festival için işler kendiliğinden yapılmaz."
    m "Özellikle ben çevrimiçi değilken~"
    show monika 1a at t21
    n 1bq "Ehh, doğru, ona yardım edecektin."
    n "Her neyse, ben zaten çıkıyorum, o yüzden..."
    m 1f "Ah, gerçekten mi?"
    m "Keşke Sayori'nin evinde biraz sohbet edebilseydik."
    m "Bir süredir sadece biz kızlar olarak vakit geçirmedik~"
    show monika 1f at t21
    n 1br "Evet, yani..."
    n "Yarın festivalde konuşuruz, sorun değil."
    n 4bq "Ama kekleri yemeden önce gelme, [player]!"
    n "Neyse, görüşürüz!"
    show natsuki at lhide
    hide natsuki 
    "Aşırı bir şekilde utanmış olan Natsuki, hızla dışarı çıkar ve Monika el sallayarak veda eder."


    # write Monika patch job here, return
    #call ch4_end
    return



label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    $yuriRoute = True
    "Evime yaklaşırken, bir anlık bir panik hissiyle karşılaşıyorum."
    mc "Yuri--?"
    show yuri 2bq at t11 zorder 2
    y "Ah..."
    y "Neyse ki..."
    mc "Biraz erken geldin..."
    mc "Özür dilerim, henüz evde değildim!"
    mc "Uzun süre bekledin mi?"
    y 1bf "Hayır, daha yeni geldim."
    y 1bh "Ama kimse kapıyı açmayınca çok gerginleşmeye başladım..."
    mc "Her zaman mesaj atabilirdin."
    mc "Eğer bilseydim, seni rahatlatır ve eve daha hızlı gelirdim."
    y 2bv "Ah... Sanırım bu doğru..."
    y "Bunu düşünmemişim... nedense."
    "Aslında bunu yapmanın normal bir şey olduğunu düşünmeliyim, ama yine de umursamıyorum."
    mc "Neyse... Hadi içeri girelim."
    mc "Bir sürü şey getirmişsin."
    y 1ba "Evet, doğru."
    y "Benden istediğin her şeyi de almayı başardın mı?"
    mc "Evet, neredeyse."
    mc "En azından, her şeyi doğru aldığımı umuyorum."
    y "Bence sorun olmaz."
    scene bg bedroom with wipeleft
    "Yuri'yi odamıza götürürken..."
    "İlk yaptığı şey etrafı merakla gözden geçirmek oluyor, bu da beni biraz gerginleştiriyor."
    show yuri 2bm at t11 zorder 2
    y "Burası o kadar temiz..."
    mc "Ahaha..."
    mc "Sen gelmeden önce temizledim, yani..."
    y 2ba "Bunu yapmak çok düşünceli bir şey."
    mc "Ah, hayır..."
    mc "Gerçekten utandım odam dağınık olsaydı, senin burada olduğunu düşündüm."
    y 1ba "Hmm..."
    y "Aslında temizlik yapmayı çok severim..."
    y "Yardımcı olurdum, seve seve temizlerdim."
    mc "Ah--"
    mc "O daha da utandırıcı olurdu!"
    show yuri 1be
    mc "Bekle, oraya bakma--!"
    "Yuri'nin bileklerinden birini tutup, masa çekmecesini açmaya başladığını fark ediyorum."
    y 3bn "A-Ah..."
    y "Üzgünüm...!"
    y 4bb "Bir şekilde düşünemedim..."
    y "Sadece dalıp gitmiştim!"
    mc "Sorun değil, sorun değil..."
    "Yuri'nin bileğinden bırakıyorum."
    show yuri 1bl
    "Yuri, iki elini kucaklayarak, ellerinin kontrolünü sağlıyor gibi."
    mc "Peki, um..."
    mc "Başlayalım mı?"
    y 2bu "Ah..."
    y "Evet..."
    y 2bf "Um, sana yardımcı olabileceğim birkaç şeyim var..."
    y "Dekorasyonlar ve diğer atmosferik iyileştirmeler."
    mc "Atmosferik iyileştirmeler...?"
    y 1ba "Biliyorsun..."
    y "Işıklandırma, aromaterapi mumları..."
    mc "Vay, hiç bu kadar ilerleyeceğini düşünmemiştim."
    y 1bc "Tabii ki."
    y "Misafirlerimizi uzak bir yere götürmek istiyorum."
    y 1ba "Ama çoğu sadece merakla gelecek..."
    y 1bj "Ve... cupcake'ler için sanırım..."
    y 1ba "Ben onları daha fazlasını istesinler diye harika bir deneyim sunmaya kararlıyım."
    mc "Harika."
    mc "Unutuyorum ki sen bayağı yoğun birisin."
    y 1bt "Ah--"
    y 2bt "Yoğun...?"
    mc "Sanırım bunu en iyi şekilde anlatan kelime bu."
    y "Bu... kötü bir şey mi?"
    mc "Hayır, hiç de değil."
    mc "Aslında bunu seviyorum."
    y 3bu "Gerçekten...?"
    y "Bu beni rahatlatıyor..."
    y "Ve biraz mutlu ediyor..."
    mc "Evet, o kadar endişelenmene gerek yok."
    mc "Biraz rahatlayabilirsin."
    y 3bl "Rahatlamak..."
    y 1bf "Ben bazı rahatlatıcı şeyler getirdim."
    y "Onları şiir etkinliği sırasında kullanacaktım..."
    mc "Vay, ne gibi?"
    y "Hadi bakalım..."
    "Yuri çantasını karıştırıyor."
    "Birkaç mum ve odun bir silindirik nesne çıkarıyor."
    y "Gelirken biraz alışveriş yaptım, bu yüzden bunlar çantamda."
    y "Pencereleri siyah kağıtla kapatıp, odayı mumlarla aydınlatmayı planladım."
    y 1ba "Bence bu harika olur, ne dersin?"
    mc "Evet, gerçekten ilginç olur."
    mc "Peki, şu odun şeyi ne?"
    y 1bf "Oh, bu mu?"
    y "Bu bir esansiyel yağ difüzörü."
    y "Aromaterapi hakkında ne kadar bilgin var?"
    mc "Hiç bilgim yok..."
    y 1ba "Ah, öyle mi?"
    y "Bu benim atmosferi olumlu hale getiren favori şeylerimden biri."
    y "Yağları ya da bitkileri seçtiğine göre, havanın ruhunu değiştirebilirsin."
    y "Bunu vücuduna da hissedebilirsin."
    y 3bm "Rahatlama, pozitif enerji, romantizm, yansıma..."
    y "Neredeyse sihir gibi."
    show yuri 3ba
    "Yuri silindiri alıp, altındaki düğmeyi basıyor."
    "Bir an içinde, üstte küçük bir delikten ince bir buhar yayılmaya başlıyor."
    mc "Vay, harika kokuyor."
    mc "Bu hangi ruh hali için uygun?"
    y 1ba "Bu Jasmine esansiyel yağı."
    y "Biraz tatlı ve çiçeksi kokuyor, değil mi?"
    mc "Evet, bunu tanımlamak iyi bir yol."
    y 1bb "Jasmine'i etkinlik için seçtim çünkü sadece rahatlama sağlamakla kalmaz."
    y "Jasmine, duygularını artırır ve vücudunda hissetmeni sağlar."
    y 1bu "Daha sıcak hissedersin ve kalbin daha hızlı atar."
    y 1ba "Bence şiirlerimizi paylaşırken bunun mükemmel olacağı kesin."
    mc "Gerçekten de uygun gibi..."
    mc "Ama sen bunun hakkında çok şey biliyorsun, bu yüzden her şeyi sana bırakacağım."
    show yuri 1bc
    "Yuri nazikçe gülümsüyor, gerçekten keyif alıyor gibi."
    "Bir kez daha çantasına ulaşarak, ince ribonlar çıkarıyor."
    show yuri 1ba
    mc "Bunlar ne için?"
    y 1bf "Şey..."
    y "Benden aldığın origami kağıtlarını aldın mı?"
    mc "Evet, burada..."
    y "Kağıtları origami katlamak için kullanmayacağız."
    y "Yapmak istediğim şey, her kağıda farklı bir kanji karakteri yazmak."
    y "Bize yaklaşık yüz tane lazım."
    mc "Vay, gerçekten mi?"
    mc "Bunları ne için kullanacağız?"
    y 2bf "Aslında, kapıdan geçerken, bunları birer birer ipe asacağız."
    y "Sonra, kağıtları asarak, kapıdan gelen bir perdelik yapacağız."
    y 2bm "Bence bu çok güzel olur."
    y "Aynı zamanda, odanın içinde yürüyen insanların dikkatini çeker..."
    y 2ba "Belki de içeri bakmaya gelmelerini sağlar."
    mc "Gerçekten yaratıcı bir fikir!"
    mc "Bunu düşündüğün için gerçekten şaşırdım, Yuri."
    y 4ba "Gerçekten mi?"
    y "Sanırım... biraz yoğun olduğum doğru..."
    y 3bu "Uhuhu."
    "Yuri kırmızı yanaklarla gülüyor."
    "Sadece ben miyim, yoksa yalnızca ikimiz olduğumuzda daha rahat mı oluyor?"
    "Belki de paylaşmaktan zevk aldığı şeyin heyecanı."
    y 1ba "İşte sana bir kalem, [player]."
    y "Herhangi bir karakter yazabilirsin."
    y "Ben ribonları keserken yardımcı olurum."
    mc "Ah, tamam."
    "Birlikte yere oturup çalışmaya başlıyoruz."
    "Her kağıda farklı bir karakter çiziyorum, kötü el yazımı idare etmeye çalışarak."
    "Yuri, uzun bir kırmızı ribon açarak istediği uzunluğa getiriyor."
    "Sonra çantasına bir kez daha uzanıyor ve cebinden bir cep bıçağı çıkarıyor."
    mc "Eh...?"
    "Bıçak oldukça güzel."
    "Gümüş sapında dalgalı bir desen oyulmuş."
    "Bıçağın kendisi hafifçe mavi renkte."
    mc "Bu sıradan bir cep bıçağı değil..."
    mc "Gerçekten çok şık."
    y 4bb "A-Ah..."
    y "Şey..."
    "Utandığından, Yuri gözlerini kaçırıyor."
    mc "Ne oldu?"
    y "Bunu garip bulacaksın..."
    mc "Yuri, ne olursa olsun, seni yargılamam için bir nedenim yok."
    mc "Herkesin farklı ilgileri var, değil mi?"
    y "Eğer garipsediğini söylemeyeceğine söz verirsen..."
    mc "Evet, söz veriyorum."
    y 2bi "Peki o zaman..."
    y "Aslında, ben biraz bıçaklardan hoşlanıyorum..."
    y "Onlar... çok güzel..."
    y 2bv "K-Kendimi tutamıyorum!"
    y "Bilmiyorum, belki de işçilik ve tehlike hissi birleşimi..."
    y 4bb "Aa, ne diyorum ben...?"
    y "Lütfen beni garip bulma..."
    mc "Ahaha."
    y "Bana mı gülüyorsun?"
    mc "Hayır, sana gülmüyorum."
    mc "Sadece, paylaşacak kadar gergin olduğunu görmek komik."
    mc "Bu... ilginç bir ilgi alanı, sanırım."
    mc "Ama bence sana çok yakışıyor."
    y 2bt "Bana mı yakışıyor...?"
    mc "Evet... Biraz yoğun, ahaha."
    mc "Buna ek olarak, gerçekten havalı bir bıçak, bunu inkar edemem."
    y 2bu "Hadi canım, öyle değil mi...?"
    "Yuri tekrar rahat bir ifade takınıyor."
    y 1ba "Bunu tutmak ister misin?"
    mc "Tabii, bir bakayım."
    "Yuri dikkatlice bıçağı bana veriyor, sapı bana doğru."
    "Onu alıp ellerimde çeviriyorum."
    "Ağırsıkmış ve oldukça sağlam hissediyor."
    "Böyle bir bıçak nereden bulursun ki...?"
    "Keskinliğini merak ettiğim için, işaret parmağımla bıçağın ucunu hissediyorum."
    mc "Aah--!"
    y 3bn "[player]--!!"
    y "Neden bunu yaptın?!"
    mc "O kadar keskin olduğunu beklemiyordum...!"
    mc "Neredeyse hiç dokunmadım."
    y "B-Benim hatam!"
    y 3bo "Sana söylemem gerekirdi..."
    y "Bu bıçak gerçekten çok keskin..."
    y "Cildi kağıt gibi kesebiliyor."
    y 2bv "Ayy..."
    "Parmağımın kenarından küçük bir damla kan sızıyor."
    "Yuri elimi alıp yaranın daha yakından bakıyor."
    y 2bt "Aah..."
    "Yuri buna bakarken belirgin şekilde hareket ediyor."
    mc "Eğer tiksiniyorsan, hemen gidip yıkayabilirim--"
    mc "A-Ah!"
    "Aniden, Yuri parmağımı ağzına alıp yarayı yalıyor."
    "Dilinin parmağımın etrafında kıvrıldığını hissediyorum."
    "Şaşırarak, içgüdüsel olarak elimi geri çekiyorum."
    y "O-Oh..."
    y 3bo "P-Pardon lütfen!"
    y "Hiç düşünmedim!"
    y 4bc "Ben..."
    "Yuri başını eğiyor, yüzü kıpkırmızı olmuş."
    mc "Yuri..."
    y "Bu yaptığım en utanç verici şey..."
    y "Bunu nasıl yapabilirim ki??"
    y "Özür dilerim, özür dilerim..."
    mc "Ah..."
    "Evet, biraz garipti ve beni şaşırttı..."
    "Ama sanırım sadece yardımcı olmaya çalışıyordu, değil mi...?"
    mc "Yuri, bence biraz fazla tepki veriyorsun..."
    y "Uuuh..."
    "Başını kaldırmıyor."
    "Belki de tüm öğleden sonra bunun etkisinden çıkamaz."
    mc "Tamam, biliyor musun..."
    "Bunu yapmak aptalca bir şey olabilir ama yine de yapıyorum."
    "Yuri'nin elini alıp karşılık olarak işaret parmağını yalıyorum."
    show yuri 3bn at h11
    y "[player]--!!"
    y "Gerçekten mi bunu yaptın?"
    mc "N-Şimdi eşitiz..."
    y 3bv "..."
    "Yuri bana garip bir şekilde bakıyor."
    mc "Ahaha..."
    mc "Bunun kötü bir fikir olacağını biliyordum..."
    "Jasmine yağının tatlı aroması olmasaydı, hava şu anda oldukça ağır olurdu."
    y 1bu "Sen çok garipsin, [player]."
    "Yuri utangaç bir şekilde kıkırdıyor."
    mc "Eh...?"
    "Yuri'nin {i}bana{/i} garip demesi?"
    "Buna karşılık veremiyorum..."
    y 1bf "Bandajlarını nerede tutuyorsun?"
    mc "Ah..."
    mc "Aslında, sanırım ihtiyacım yok."
    mc "Çok küçük bir kesikti."
    mc "Bak, zaten kanamayı durdurdu."
    y 1ba "Anladım..."
    y "Bu rahatlatıcı."
    "Gerilim hızla kalktı."
    "Herkes kendi işine devam ediyor."
    "Yuri'nin bıçağı ile kurdelesini hiç zorlanmadan kesmesini izliyorum."
    "Ben de kanjiler üzerinde ilerlemeye devam ediyorum."


    scene bg bedroom with wipeleft_scene
    "Kağıdı kurdelalara yapıştırmayı bitirdikten sonra, hepsini yan yana diziyoruz."
    "Beklediğimden daha güzel görünüyor ve kapı perdesi olarak çok etkili olacak."
    mc "Harika görünüyor."
    mc "Bunu düşünmen çok iyi, Yuri."
    show yuri 1bq at t11 zorder 2
    y "Ah, teşekkürler..."
    y "Aslında sadece internette gördüm, o kadar."
    y 1ba "Bir sonraki göreve geçmeye hazır mısın?"
    mc "Evet, hadi yapalım."
    mc "Ne düşünüyorsun?"
    y "Bir afiş yapmak istiyorum."
    y "Bu yüzden sana boya tabletlerini almanı istemiştim."
    mc "Aa, doğru."
    "Yuri'nin bana aldırdığı şeylerden biri su renkli boya tabletleri kitiydi."
    y 1bf "Her bir tableti koymamız için altı bardak suya ihtiyacımız olacak."
    y "Bunları getirmemi ister misin?"
    mc "Tabii, hiç sorun değil."
    mc "Altı bardak su..."
    mc "Bir dakika içinde döneceğim."
    y 1ba "Çok teşekkür ederim."
    y 2bf "Oh, ve sadece biraz su yeterli."
    y "Bardakları fazla doldurursan, çok seyrelir."

    scene bg bedroom with wipeleft_scene
    "Yuri'nin önerisini dikkate alarak, büyük bardaklar yerine küçük plastik banyo bardakları kullanmaya karar veriyorum."
    "Onları, damlayan boyayı tutması için bir tabağa koyup, odamıza geri getiriyorum."
    mc "Yuri?"
    show yuri 1bd at t11 zorder 2
    y "Evet?"
    "Yuri, hızlıca kolunun manşetini açıyor, sonra kolunu geri çekip örtüyor."
    mc "Aa, bir şey yok..."
    mc "Yüzün biraz kızarmış."
    mc "Burada çok sıcak mı, yoksa başka bir şey mi var?"
    y 3bq "Aa--"
    y "Hayır, hiç yok!"
    y "Bir şey yok, yani..."
    y "Hadi boyayı karıştıralım."
    "Yuri aceleyle beni geçiştirip, kendi başına tabletleri açıyor, bardaklara atıyor."
    y 1ba "Yani..."
    y "Çok basit ama çok güzel görünen bir şey yapmayı düşündüm."
    y "Bir geçiş yapmayı düşünüyorum, afişin üzerine..."
    y "Önce bir güneş doğumu renkleri, sonra gündüz, ardından akşam ve gece renkleri."
    y "Kuruduktan sonra afişin üzerine ilham verici bir alıntı yazacağım."
    y "Bunu, sınıfın önündeki kürsünün arkasına asabiliriz."
    mc "Ah, harika."
    mc "Ne yazacaksın?"
    y 2bm "Hmm..."
    y "...Seni şaşırtmak daha eğlenceli olacak."
    "Yuri bana gülümsüyor."
    mc "Öyle diyorsan..."
    show yuri at thide zorder 1
    hide yuri
    "Afişi açtıktan sonra, Yuri ve ben karşılıklı diz çöküyoruz, böylece birbirimizin yolunu kesmiyoruz."
    "Yuri bir fırça kullanarak afişin üzerine, boyarken rehberlik edecek birkaç farklı renk noktası koyuyor."
    mc "Burası bana ilkokulu hatırlatıyor gibi..."
    "Su renkleriyle afiş boyamak, o zamanlar yaptığımız sanat sınıfı projelerine çok benziyor."
    "Rahatlatıcı."
    show yuri 2bt at t11 zorder 2
    y "Ah..."
    y "Eğer bu çok çocukça hissediyorsa özür dilerim...!"
    mc "Hayır, bunu demek istemedim."
    mc "Aslında oldukça eğlenceli, biliyor musun?"
    y 1bs "...Evet."
    y "Gerçekten eğlenceli."
    y "Senin de böyle hissetmene sevindim."
    "Yuri bir anlığına boyamayı bırakıyor, kendi kendine düşünüyor."
    y 2bl "Benim için..."
    y "Çılgın şeyler yapmaya gitmeme gerek yok eğlenmek için."
    y "Aslında, genellikle hiç gitmek istemem."
    y 2bf "Bir tek başkasıyla vakit geçirebildiğimde hoşlanırım..."
    y "Basit bir şey olsa bile, mesela kitap okumak - çok konuşmasak da fark etmez."
    y 2ba "Yanımda bir arkadaşım olduğu zaman her şey biraz daha güzel hissediyor."
    y "Sanırım benim için mutluluk bu kadar basit."
    mc "Öyle mi...?"
    "Yuri ve ben oldukça farklı olsak da, söylediklerini anlıyorum."
    "Ben de anime ve oyunlar gibi şeyler konusunda böyle hissediyorum, sadece birisiyle deneyimi paylaşmak beni mutlu ediyor."
    mc "San sanırım ben de aynı şekilde hissediyorum."
    "Yuri nazikçe gülümsüyor."
    y 1bm "Bunu anlayacağını biliyordum..."
    "Yuri afişin üzerine eğilip kullanılmamış bir fırça alıyor."
    "Ama ben aynı anda hareket ediyorum, bu yüzden kafam başına çarpıyor."
    y 3bn "Kya--!"
    mc "S-Sorry!"
    "Yuri geriye çekiliyor, ben de şaşkın bir şekilde ellerimi kaldırıyorum."
    mc "Canın yandı mı?"
    y 2bv "H-Hayır, canım yanmadı."
    y "Sadece korktum... o kadar."
    y "Üzgünüm, sana bunu sormalıydım..."
    mc "Senin suçun değil."
    mc "Aa, yüzün..."
    "Yuri'nin yüzünde ve boynunda boyadan damlacıklar var."
    y 2bt "Yüzümde bir şey var mı?"
    mc "Evet, sana yanlışlıkla boya sıçradı..."
    mc "Özür dilerim, tamamen benim hatam!"
    mc "Hemen bir havlu getireyim."
    show yuri at thide zorder 1
    hide yuri
    "Hızla dışarı çıkıp küçük bir havlu aldım ve sıcak suyla nemlendirdim."
    "Odaya geri döndüm ve onun önünde tekrar diz çökerek, havluyu elime aldım."
    $ persistent.clear[5] = True
    scene y_cg3_base with dissolve_cg
    mc "İşte..."
    "Yuri'nin yüzünü ve boynunu havluyla nazikçe sildim."
    show y_cg3_exp1 at cgfade
    y "Ah--"
    mc "Bir şey mi var?"
    y "Sıcak... beklemiyordum."
    mc "Üzgünüm..."
    mc "Soğuk su kullanmak istemedim."
    "İşim bitince, elimi geri çekmeye başlıyorum."
    "Ama Yuri aniden bileğimi tutuyor."
    hide y_cg3_exp1
    y "Bekle--"
    mc "Eh?"
    show y_cg3_exp1 at cgfade
    y "Sadece... biraz daha."
    y "Gerçekten çok hoş hissediyorum..."
    mc "Ah..."
    "Elimi Yuri'nin boynunda sabit tutuyorum."
    hide y_cg3_exp1
    "Gözlerine bakıyor."
    "Bu, kitap okurken tanıdığım o yoğun ifade..."
    "Sanki kafasında kaybolmuş, kendi düşüncelerine dalmış gibi."
    "Hafifçe nefes alıyor, dudakları hafif aralanmış."
    "Ne oluyor...?"
    "Beni bu sersemlemiş hissettiriyor mu? Yoksa Jasmin yağının kokusu mu?"
    "Yuri'nin bileğimi saran nazik parmakları, kolumda bir karıncalanma hissi bırakıyor."
    "Ve aniden, yüzü bir anda bana çok daha yakın gibi görünüyor..."
    y "Ah..."
    "Yuri yavaşça geri çekiliyor."
    y "Üzgünüm..."
    y "Bugün biraz başım döndü."
    y "Neyse ki, boş boş düşünmeye başladım..."
    mc "B-Bir şey değil..."
    scene bedroom with dissolve_cg
    "O an, başladığı gibi bitiyor."
    "Yuri tekrar fırçasını alıyor."
    "Ama hareketleri biraz daha sakar, sanki odaklanmakta zorlanıyor."
    "Ben de sessiz kalıyorum, az önceki olayı görmezden gelmek zorundayım."
    "Kendi fırçamı çekinerek alıp, Yuri'nin örneğini takip etmeye devam ediyorum."

    scene bedroom with wipeleft_scene
    mc "Sanırım bu kadar yeter..."
    "Geceyi beyaz noktalarla dolduruyorum, sanki yıldızlar gibi."
    "Bütün pankarta baktığımda, oldukça güzel ve doğal görünüyor."
    show yuri 1ba at t11 zorder 2
    y "Beklediğimden daha güzel oldu."
    y "Sonuçlardan gerçekten çok memnunum."
    mc "Evet, bende."
    mc "Şimdi yazı ekleyecek misin?"
    y 1bf "Ah, henüz değil..."
    y "Önce kuruması lazım."
    mc "Doğru, ama bu ne kadar sürecek?"
    y 2bh "Hmm..."
    y "Sanırım en iyisi buraya bırakmak ve sabah getirdiğinde tamamlamak."
    y 2bf "Sınıfta, etkinlik başlamadan önce yazıyı eklerim."
    y "Tamam mı?"
    mc "Tabii ki, sorun değil."
    y 1ba "Harika."
    y "O zaman..."
    y "Burada yapacak başka bir şey kalmadı gibi."
    mc "Of."
    y 1bc "Ahaha."
    y "Bittiği için mutlu musun?"
    y 1ba "Beni böyle hissettirdiğimi düşünmüştüm, ama... gerçekten keyif aldın mı?"
    mc "Ah, hayır, öyle demek istemedim."
    mc "Sadece her şeyi bitirmiş olmamıza sevindim."
    y 2ba "Anladım."
    y "Ben de."
    y "Biraz zaman konusunda endişeliydim..."
    y "Yemek hazırlamam gerek."
    mc "Ah..."
    mc "Yani hiç zamanın kalmadı mı?"
    "Aslında, iş bitince biraz ekstra zamanımız olmasını umuyordum..."
    y 2bl "Hmm..."
    y "..."
    "Yuri kendi kendine düşünüyor."
    y 3bv "B-Bence daha fazla beklemek bana sorumsuzca gelir..."
    y "Üzgünüm!"
    y "Keşke daha fazla zaman olsaydı..."
    mc "Sanırım suç bende."
    mc "Yavaş çalıştığım için özür dilerim."
    y 1bt "Hayır, kesinlikle suçun yok."
    y "Ve... önemli olan her şeyi bitirmiş olmamız, değil mi?"
    mc "Evet..."
    y 1bu "O zaman..."
    y "Hayal kırıklığına uğramamalıyım... ya da bir şey."
    "Yuri, bütün eşyalarını toplarken biraz moralini bozmuş gibi görünüyor."
    "Nedenini anlıyorum."
    "Sanırım, arkadaşlarıyla rahatça vakit geçirme fırsatını nadiren buluyor."
    "Ama bu son kez olduğu anlamına gelmiyor..."

    scene bg house with wipeleft_scene
    "Yuri eşyalarını toparladıktan sonra, onu ön kapıdan dışarıya kadar uğurladım."
    show yuri 1ba at t11 zorder 2
    y "Bugün beni kabul ettiğiniz için çok teşekkür ederim."
    mc "Rica ederim, yardımcı olabildiysem ne mutlu."
    mc "Yarın getirmemi istediğin başka bir şey olursa, bana haber ver."
    y "Tabii."
    y 1bu "O zaman... "
    "Yuri bir anlık tereddütle duraksıyor."
    y 2bu "Sanırım... Yarın görüşürüz."
    mc "Bekle--"
    show yuri 2bt
    "Düşünmeden söyledim gibi oldu."
    mc "Bugün için..."
    mc "Çok fazla zamanımız olmamış olması sorun değil."
    mc "Çünkü bunu tekrar yapabiliriz."
    mc "Ne zaman istersen, gelebilirsin ya da dışarıya gidebiliriz--"
    mc "Ah, dışarıya çıkmayı pek sevmediğini unuttum--"
    show yuri 2bs
    "Kelimelerim takılırken, Yuri sadece utangaçça gülümsüyor."
    mc "Neyse..."
    mc "Ne demek istediğimi biliyorsun, yani..."
    y 1bs "Çok düşüncelisin, [player]."
    "Yuri bir adım daha yaklaşıyor ve sonra kısa bir süre elimi sıkıyor."
    show yuri 2bs at face(y=600) with dissolve
    stop music fadeout 2.0
    y "Bunu sana karşı çok beğeniyorum..."
    mc "Peki..."
    "Buna nasıl cevap vereceğimi bilemiyorum."
    "Ama buna bile fırsatım olmadan, Yuri aniden geri çekiliyor."
    show yuri 3bn at t11 zorder 2
    y "M-Monika--?!"
    show monika 1j at f21 zorder 3
    show yuri at t22 zorder 2
    mc "Eh?!"
    m "Ah..."
    m 1k "Beni yolundan alıkoymayın, ahaha."
    mc "Monika--!"
    mc "Sayori sadece online olarak yardımcı oluyordu--"
    m "Fikrimi değiştirdim ve gelmeye karar verdim."
    mc "Neyse, şu anda biz--"
    m 3b "Oh, biliyorum."
    m "Merak etme, sırrınız bende güvende."
    m 1b "Bir kelime bile etmeyeceğim."
    m "Sayori'ye doğru yoldayım, festival için işimiz kendiliğinden yapılmaz."
    m "Özellikle ben online değilken~"
    show monika 1a at t21
    y 3bq "U-um..."
    y "Neyse, görüşmek güzel..."
    y 3bv "Üzgünüm, ama ben zaten gitmek üzereydim!"
    m 1g "Gerçekten mi?"
    m "Ah, ne yazık..."
    m "Bir süredir sadece biz kızlar kaldık~"
    show monika 1f at t21
    y 2bt "Üzgünüm..."
    y "Ama yarın festivalde hep birlikte olacağız, o yüzden..."
    y "Bu sorun olmaz, değil mi?"
    show yuri at t22 zorder 2
    show monika at f21 zorder 3
    m "Tabii, tabii."
    show monika 1a 
    show monika at t21 zorder 2
    show yuri at f22 zorder 3
    y "E-evet, o zaman..."
    y "Yarın görüşürüz!"
    show yuri at lhide 
    hide yuri
    "Açıkça utanan Yuri, aceleyle uzaklaşıyor."
    "Monika, ona el sallayarak veda ediyor."



    # write Monika patch job
    #call ch4_end
    return




label ch4_end:

    # Monika'nın bölüm işini buraya yazıyoruz
    show monika 1d at t32
    m "Sayori değil, ha?"
    show monika 1c at t32
    mc "Ben..."
    m 1d "Zaten sana neler yaşadığını söyledi, değil mi?"
    "Ağzımı açmaya çalışıyorum ama hiçbir şey çıkmıyor."
    "Monika'nın nasıl bildiğini sormayı düşünüyordum ama büyük ihtimalle Sayori, Monika'ya bir şeyler anlatmıştır."
    "Sonuçta, onlar yakın arkadaş gibi görünüyorlar."
    "Ben..."
    m 1r "Merak etme."
    mc "Ne...?"
    m 1i "Birine veya bir şeye kafanı takacaksan, yarım yamalak yapma."
    m "Yani, merak etme."
    m "Benden hallederim, senin önündekilere odaklanabilmen için."
    m 1j "Hehehe."
    "Monika gizemli bir şekilde gülüyor."
    m 1n "Herkesi kurtarmaya çalışsan da, her seferinde sadece birini kurtarabilirsin, değil mi?"
    m 1r "Sanırım senin de sınırların var."
    m "Ya da belki böyle olsun istedin..."
    # m "Sonuçta, sen <i>harem</i> tipi biri gibi görünmüyorsun."
    m "Ama pek önemli değil."
    m 1i "Senin yapamadığını ben hallederim."
    m 1p "Zaten pek işim yok, değil mi?"
    mc "Monika--"
    m 1d "Hm?"
    mc "E-um..."
    mc "Aslında ne diyeceğimi pek bilmiyorum ama... teşekkür ederim."
    m 5a "Hehehe."
    m "Tamam."
    m "Yarın festivalde görüşürüz, [player]."
    hide monika with wiperight
    "Bununla birlikte, Monika Sayori'nin evine doğru giderken el sallayarak ayrılıyor."
    "Tamam..."
    "Sanırım yarınki festival için dinlenmeye gitmeliyim."




    return